"""The role card: who someone IS, in one line, for "who can help with X".

Pure and dependency-free so it can be tested without torch. The builder
composes it from the profile summary and the person's recorded roles; it is
never generated by an LLM.
"""
from __future__ import annotations

import re

_SENTENCE_END = re.compile(r"(?<=[.!?])\s+")
# The profile prompt leads with the role, so the first sentence is the card.
# Bio "about" paragraphs sometimes have no sentence break at all; cap them.
MAX_LEAD = 300


def lead_sentence(summary: str | None, display_name: str | None = None) -> str:
    """The summary's first sentence. Bio-only summaries open with a bare
    "Name." — skip it, or the card would say the name twice and nothing else."""
    s = (summary or "").strip()
    name = (display_name or "").strip()
    if name and s.startswith(f"{name}."):
        s = s[len(name) + 1:].strip()
    lead = _SENTENCE_END.split(s, maxsplit=1)[0] if s else ""
    if len(lead) > MAX_LEAD:
        lead = lead[:MAX_LEAD].rsplit(" ", 1)[0] + "…"
    return lead


def compose_card(
    display_name: str | None,
    summary: str | None,
    linkedin_role: str | None = None,
    company_role: str | None = None,
) -> str | None:
    """Name + lead sentence + any recorded role the lead does not already say.

    Circle labels are deliberately NOT included: circles are the answer key
    the card is measured against, and the find_people tool looks them up
    directly. Returns None when there is nothing but a name."""
    name = (display_name or "").strip()
    text = name + "."
    lead = lead_sentence(summary, name)
    if lead:
        text += f" {lead}"
    for extra in (linkedin_role, company_role):
        extra = (extra or "").strip().rstrip(".")
        if extra and extra.lower() not in text.lower():
            text += f" {extra}."
    return None if text == name + "." else text
